### ISSUE TITLE
Missing Client_Secret

### ISSUE THREAD

**Issue by kemper451** [au2mator/au2mator-PS-Templates#1]
Your Send-TeamsCard function seems to be missing the Client_Secret portion.  It threw errors until I modified to this:

    $tokenBody = @{  
        Grant_Type = "password"  
        Scope      = "user.read%20openid%20profile%20offline_access"  
        Client_Id  = $clientId  
        Client_Secret  = $clientsecret  
        username   = $User
        password   = $pw
        resource   = "https://graph.microsoft.com"
    }

**Comment by Seidlm** [comment]
fixed with 1.5
